meta_product_name: "WhyNot?"
meta_title: "WhyNot? - The Best app to meet new friends"
meta_description: "This is the best app to meet new friends !"
# meta_image: "https://res.cloudinary.com/ambroise/image/upload/v1583331336/D1061_193_548_1200_uosx4f.jpg" # should exist in `app/assets/images/`
meta_image: "https://res.cloudinary.com/duv3g4cfp/image/upload/v1583408837/cdfm4ca8v6fghaaxf47f.jpg"

