meta_product_name: "Product Name"
meta_title: "Product name - Product tagline"
meta_description: "Relevant description"
meta_image: "https://res.cloudinary.com/ambroise/image/upload/v1583330375/friends-chatting-while-sitting-sofa_23-2148143190_gtnkxj.jpg" # should exist in `app/assets/images/`
