meta_product_name: "Product Name"
meta_title: "Product name - Product tagline"
meta_description: "Relevant description"
meta_image: "https://res.cloudinary.com/ambroise/image/upload/v1583331336/D1061_193_548_1200_uosx4f.jpghttps://res.cloudinary.com/ambroise/image/upload/v1583331336/D1061_193_548_1200_uosx4f.jpg" # should exist in `app/assets/images/`
